-- vim.keymap.set("n", "<C-w>h", ":FocusSplitLeft<CR>")
-- vim.keymap.set("n", "<C-w>j", ":FocusSplitDown<CR>")
-- vim.keymap.set("n", "<C-w>k", ":FocusSplitUp<CR>")
-- vim.keymap.set("n", "<C-w>l", ":FocusSplitRight<CR>")
