-- return require("packer").startup(function(use)
-- 	use("wbthomason/packer.nvim")
--
-- 	use({
-- 		"nvim-treesitter/nvim-treesitter",
-- 		run = ":TSUpdate",
-- 	})
--
-- 	use({ "tjdevries/colorbuddy.vim", requires = {
-- 		{ "tjdevries/gruvbuddy.nvim" },
-- 	} })
--
-- 	use({
-- 		"nvim-telescope/telescope.nvim",
-- 		tag = "0.1.0",
-- 		requires = { { "nvim-lua/plenary.nvim" } },
-- 	})
--
-- 	use({
-- 		"VonHeikemen/lsp-zero.nvim",
-- 		requires = {
-- 			-- LSP Support
-- 			{ "neovim/nvim-lspconfig" },
-- 			{ "williamboman/mason.nvim" },
-- 			{ "williamboman/mason-lspconfig.nvim" },
--
-- 			-- Autocompletion
-- 			{ "hrsh7th/nvim-cmp" },
-- 			{ "hrsh7th/cmp-buffer" },
-- 			{ "hrsh7th/cmp-path" },
-- 			{ "saadparwaiz1/cmp_luasnip" },
-- 			{ "hrsh7th/cmp-nvim-lsp" },
-- 			{ "hrsh7th/cmp-nvim-lua" },
--
-- 			-- Snippets
-- 			{ "L3MON4D3/LuaSnip" },
-- 			-- Snippet Collection (Optional)
-- 			{ "rafamadriz/friendly-snippets" },
--
-- 			-- Format
-- 			{ "mhartington/formatter.nvim" },
-- 		},
-- 	})
--
-- 	use({
-- 		"smjonas/live-command.nvim",
-- 		config = function()
-- 			require("live-command").setup({
-- 				commands = {
-- 					Norm = { cmd = "norm" },
-- 				},
-- 			})
-- 		end,
-- 	})
--
-- 	-- Packer
-- 	use({
-- 		"folke/noice.nvim",
-- 		config = function()
-- 			require("noice").setup({
-- 				-- add any options here
-- 			})
-- 		end,
-- 		requires = {
-- 			"MunifTanjim/nui.nvim",
-- 			"rcarriga/nvim-notify",
-- 		},
-- 	})
--
-- 	if packer_bootstrap then
-- 		require("packer").sync()
-- 	end
-- end)
